version: "3"

services:
  rollbot:
    build: .
    image: "hannilo/rollbot-py"
    container_name: rollbot
    restart: always
    logging:
      options:
        max-file: 3
        max-size: 10m
    volumes:
      - "./.env:/.env:ro"
